### ISSUE TITLE
[Suggestion] Make you able to reverse search images on right click (like TinEye extension)

### ISSUE THREAD

**Issue by Grooty12** [kagisearch/browser_extensions#12]
Like this:
![image](https://github.com/kagisearch/browser_extensions/assets/85930101/70a34b1b-fea5-4a4f-9b20-fb6bae30fe5a)

It wouldn't be more than a couple lines of code I think, so I could probably add it myself if needed

**Comment by vprelovac** [comment]
Yes, feel free to submit a PR.

**Comment by hmnd** [comment]
@Grooty12 FYI support for Kagi in the Search by Image extension was added a couple months ago: https://github.com/dessant/search-by-image/issues/248
