### ISSUE TITLE
Firefox Extension update is prompting for new, very broad, permissions

### ISSUE THREAD

**Issue by kepstin** [kagisearch/browser_extensions#13]
It seems like something has changed in the extension manifest in a recent update which is resulting in Firefox re-prompting for permissions before installing the update. The two new permissions being asked for are:

* Block content on any page
* Access browser tabs

Given the purpose that I installed the extension for - to allow using Kagi search in private windows or multi-account containers - these permissions seem overly broad, and I do not wish to grant them. The extension has worked fine until now with only permission to "Access your data for kagi.com" granted.

If these permissions are for some new optional extension feature, the permissions should be [requested at runtime](https://extensionworkshop.com/documentation/develop/request-the-right-permissions/#request-permissions-at-runtime) since they are not required for basic extension functionality.

See the Firefox docs [Requesting the right permissions](https://extensionworkshop.com/documentation/develop/request-the-right-permissions/) and [Test permission requests](https://extensionworkshop.com/documentation/develop/test-permission-requests/) for details about how the warning Firefox shows during upgrades, how it categorizes permissions, and how to test.

**Comment by kepstin** [comment]
Some specific notes: I suspect that the `tabs` permission could be switched out for `activeTab` without reducing the functionality of the universal summarizer. Firefox does not prompt for `activeTab` permission.

I think the "Block content on any page" is coming from `declarativeNetRequest` - it's not clear why exactly that is included in the manifest? From a cursory search, I don't see any use of the [declaratives rules for evaluating and modifying network requests](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/declarativeNetRequest).

**Comment by vprelovac** [comment]
Thanks for the heads up. AFAIk the tabs permissions were added to support the new summarize page feature. 

It appears it could have been handled more incrementally permission wise. 

If anyone wants to submit a PR to fix these you are welcome! Otherwise we will have someone look at this.

**Comment by vprelovac** [comment]
New Firefox version updated with your PR. Thanks again!
