### ISSUE TITLE
Chrome extension update permissions

### ISSUE THREAD

**Issue by gtebbutt** [kagisearch/browser_extensions#17]
Similar to https://github.com/kagisearch/browser_extensions/issues/13, the Chrome extension is now prompting for access to full browsing history and is automatically disabled by the browser if that isn't granted - this looks as though it [comes from](https://developer.chrome.com/docs/extensions/mv3/permission_warnings/) the recently added `tabs` permission in the manifest. Assuming that's only used for the summariser, I think it should be possible to replace it with [`activeTab`](https://developer.chrome.com/docs/extensions/mv3/manifest/activeTab/), which will prompt for access when used rather than requiring it globally. 

I also noticed that `declarativeNetRequest` is listed as "Block content on any page" in the user facing permissions. Since it only seems to be used for injecting the auth token on kagi.com it could probably be switched to `declarativeNetRequestWithHostAccess` as it is on Firefox.

**Comment by vprelovac** [comment]
@gtebbutt Can you review the current code after PRs and submit a PR if needed
