### ISSUE TITLE
Safari Extension Should Not Ask for All Websites

### ISSUE THREAD

**Issue by ocdtrekkie** [kagisearch/browser_extensions#29]
Hello! I installed the Safari extension today on my iPhone and the requested permissions are very scary: It wants access to read and modify all websites. Not only is this a big privacy and security risk, it's totally unnecessary:

When I visit my default search provider, DuckDuckGo, and click on the Kagi button, it asks for permission to read and modify *just* DuckDuckGo, and this works perfectly for the search bar, and is a setting I am much more comfortable with.

The instructions in the app should encourage people to grant the least necessary privilege, not the widest. The extension should instruct people to run a search and then press the Kagi extension from the results page.

**Comment by mhsdef** [comment]
I wasn't going to use the extension until @ocdtrekkie spelled this approach out in Discord. Hearty +1 that this should be the instructions on the site.
