### ISSUE TITLE
When searching an extra empty search tab opens.

### ISSUE THREAD

**Issue by Wielding** [kagisearch/browser_extensions#35]
Every once in a while on Firefox nightly (at least a couple of times a day) when I type my search criteria in the Firefox URL bar and hit enter, an extra tab opens up with an empty search url: "https://kagi.com/search?q=&l=6" and becomes focused.  The search successfully executes in the tab that was active when I hit enter, so I have to close the newly created empty search tab to get back to my actual results, which is a bit annoying.  I have tried unsuccessfully to identify any pattern to predict when this will happen.

**Comment by Wielding** [comment]
I apologize for the report, it does not seem to be the extension.  I removed the extension and manually added kagi as my search to Firefox and it still happened.  So it seems that somehow kagi.com is opening a new tab after the real search results are displayed.  What else would add the &l=6 parameter which seems to select a lens?   I can't reproduce this on any other browser.

**Comment by vprelovac** [comment]
We do not do that or have heard of this situation before, so it is likely related to your settings/browser. Have you tried in a different browser to rule out Kagi?

**Comment by Wielding** [comment]
It is very strange.  It does not happen on any other browser and it happens on both Windows and Linux on Firefox nightly.  I agree at this point it is probably browser or setting related.  I will keep researching.  I disabled all extensions and it still happens, but less often.  On a new profile, it stopped so I will keep investigating and close this issue.
