### ISSUE TITLE
Extension does not keep me logged in with Firefox Private Browsing

### ISSUE THREAD

**Issue by Inityx** [kagisearch/browser_extensions#41]
In Firefox on Windows, Pop!_OS, and Android, the extension does not keep me signed in in private windows.

The extension shows that it is authorized with my login token, and Firefox states that it "Can always read and change data on this site" for kagi.com, but the site prompts me to log in before I can search.

I am able to successfully use the Summarize function, and I have tried manually re-entering the login token, but the problem persists.

**Comment by BrunoBernardino** [comment]
Thanks for reporting this @Inityx. Can you confirm if this is the same issue as reported in https://github.com/kagisearch/browser_extensions/issues/27#issuecomment-1735185298 ? Basically, do you have the option to delete browser history on quit?

**Comment by Inityx** [comment]
Nope, my normal Firefox settings do not clear any data on quit.

**Comment by Inityx** [comment]
Hmm... after updating to v0.4.0, it appears to now be working on Windows and Pop_OS!, but the problem still appears on Android.

**Comment by BrunoBernardino** [comment]
I'm glad you're no longer having issues on the desktop version. As for Android, it has a few known issues, being tracked at #3 . It does not set the session _at all_ there.

**Comment by MatthiasKunnen** [comment]
@BrunoBernardino, #3 seems to 404, what happened to it?

**Comment by BrunoBernardino** [comment]
No idea. I also see it 404. @vprelovac ?
