### ISSUE TITLE
Context menu image search processes URLs as texts

### ISSUE THREAD

**Issue by Frederick888** [kagisearch/browser_extensions#42]
For example, if you right click on my profile picture and reverse search for it, it shows a bunch of pictures that don't look like it at all:

<img width="978" alt="image" src="https://github.com/kagisearch/browser_extensions/assets/4507647/0b4b0e8d-417b-420e-adc5-fe81da181de0">

I guess this is because the URL is treated as text.

In Kagi if I copy the URL manually into the reverse search input,
<img width="783" alt="image" src="https://github.com/kagisearch/browser_extensions/assets/4507647/8ebdf816-d4a3-4b07-b02f-0bea770e308c">
now it starts showing similar pictures:
<img width="871" alt="image" src="https://github.com/kagisearch/browser_extensions/assets/4507647/e2db49bb-e86e-4009-98e5-f466f3f88472">

**Comment by vprelovac** [comment]
@alabhyajindal Can you check this

**Comment by alabhyajindal** [comment]
Thanks for raising the issue! #43 should fix it.

https://github.com/kagisearch/browser_extensions/assets/52493077/eaf32a0e-c014-4641-aba9-c9833097d4d0
