### ISSUE TITLE
Right click summarize should open popup window

### ISSUE THREAD

**Issue by jacksongoode** [kagisearch/browser_extensions#45]
Right now it redirects to the summarize page, and only from the addon click will the popup appear.

**Comment by BrunoBernardino** [comment]
@vprelovac do you think it's worth these behave the exact same? Since you're not dealing with the extension directly, it seemed OK to me to have the context menu option simply open the summarizer URL in a new tab.

**Comment by vprelovac** [comment]
@BrunoBernardino yes it should behave the same as extension
