### ISSUE TITLE
Login in private Windows stopped working

### ISSUE THREAD

**Issue by philippludwig** [kagisearch/browser_extensions#47]
Since a couple of days, I need to login in private windows everytime. I have version 0.4.1 of the extension on Firefox 115.4.0esr, Gentoo Linux.

**Comment by vprelovac** [comment]
Does this help?

If you run into a problem of not being logged in to Kagi on incognito sessions, try manually setting your session token. If that doesn't work, try disallowing it on Incognito, saving the session token manually, and then re-allowing it again.


from https://help.kagi.com/kagi/getting-started/setting-default.html#browser_extension

**Comment by philippludwig** [comment]
Yes, this fixed it. Thank you very much, I should have checked the help section before opening this issue.
