### ISSUE TITLE
Unclear license

### ISSUE THREAD

**Issue by Atemu** [kagisearch/browser_extensions#48]
Hi,

on the Firefox add-on page it says the extension is licensed under MPL-2.0 but there is no license file in this repo.

Confusingly, the package.json claims the project is licensed under the MIT license:

https://github.com/kagisearch/browser_extensions/blob/ee17ff17cae3d1397c7dce2671718fc3dbcabd41/package.json#L22

Please add a license file to clarify and clean up the metadata.

**Comment by BrunoBernardino** [comment]
The license has been fixed in the extension page too, thanks for reporting this.

**Comment by Atemu** [comment]
Thanks :)
