### ISSUE TITLE
Summary API key keeps unsetting itself so changing the model is impossible

### ISSUE THREAD

**Issue by kirawi** [kagisearch/browser_extensions#63]
Pretty much the title. It would be nice to either not reset the API key or allow users to change the model without needing to enter the API key. This could also be specific to my configuration somehow as I'm not able to use Kagi in private mode with my token without giving it permission to kagi.com

**Comment by vprelovac** [comment]
What version extension? What browser?

**Comment by kirawi** [comment]
Firefox developer 0.5.0

**Comment by BrunoBernardino** [comment]
@kirawi can you please try, in the extension's permissions/settings, disabling the "Run in Private Windows" toggle, saving the token and API key, then enabling it again?

**Comment by kirawi** [comment]
It unfortunately did not work.

**Comment by BrunoBernardino** [comment]
I'm out of ideas, here. Are there any errors anywhere? Does the API key disappear instantly (the next time you open the extension), or only after you close the browser?

**Comment by kirawi** [comment]
I can't find reproduction steps for this issue, so I'll close it and instead hardcode the values into a fork of the extension.

**Comment by BrunoBernardino** [comment]
> I can't find reproduction steps for this issue, so I'll close it and instead hardcode the values into a fork of the extension. No other extension/site could inspect the tokens if I hardcode them, right?

Right.
