### ISSUE TITLE
FEATURE: Close Kagi summarieser popup on <ESC>, and/or add "Close" button

### ISSUE THREAD

**Issue by eyJhb** [kagisearch/browser_extensions#67]
It would be really nice, if the Kagi summarieser popup would close when `<ESC>` is pressed, or add a close button
If both things could be added, it would be really nice.

**Comment by alabhyajindal** [comment]
Are you talking about this popup? 

![image](https://github.com/kagisearch/browser_extensions/assets/52493077/8fc34ba6-680d-45b3-b4b4-780dc63d4283)

**Comment by eyJhb** [comment]
Yes exactly, but it's not a given, that there are any window manager icons for closing the popup, ie. this is how it looks for me.

![image](https://github.com/kagisearch/browser_extensions/assets/25955146/76a34066-cdbf-44a4-8b8c-66aedd95d237)

**Comment by alabhyajindal** [comment]
@BrunoBernardino what do you think should be done here? I would like to help out if you want.

**Comment by BrunoBernardino** [comment]
@alabhyajindal you can add a window keydown listener for Esc in the summarizer result window and also a close button with a click listener for `window.close()`.
