### ISSUE TITLE
Loggeed out in Firefox private windows

### ISSUE THREAD

**Issue by drguildo** [kagisearch/browser_extensions#74]
The [Firefox add-on page](https://addons.mozilla.org/en-GB/firefox/addon/kagi-search-for-firefox/) says that it supports "automatically logging in to Kagi in private browsing windows", but this doesn't work for me. When I attempt to search from a private window, I get the login page.

I have "Run in Private Windows" enabled, as well as the "Access your data for https://kagi.com" permission.

I'm using version 0.6.0 of the add-on with Firefox 123.0.

**Comment by BrunoBernardino** [comment]
Thanks for reporting this, @drguildo, can you please try, in the extension's permissions/settings, disabling the "Run in Private Windows" toggle, saving you personal access token in the extension, then enabling it again, to see if that works?

**Comment by BrunoBernardino** [comment]
@drguildo it wasn't, but I'm happy that worked out anyway. Thank you!

**Comment by drguildo** [comment]
Should this issue really be closed? What you suggested is a workaround, not a fix.

**Comment by BrunoBernardino** [comment]
@drguildo this is a problem with Firefox itself, not the extension, as far as we can tell. It's been reported a few times, and there's a section in the help docs for it: https://github.com/kagisearch/browser_extensions/issues/47#issuecomment-1799581079

**Comment by drguildo** [comment]
Would adding an option field to the extension where you could manually add your session token be possible? That could then be used to generate the search URL and save having to log in.

It'd be nice if it all happened automatically, but from what you say it doesn't sound like that's currently possible. This way would at least be easier than messing around toggling browser settings on and off.

**Comment by BrunoBernardino** [comment]
@drguildo could you elaborate? Opening the extension settings already shows you a field to manually add your session token.

**Comment by drguildo** [comment]
My bad, I was looking in the wrong place.
