### ISSUE TITLE
Kagi extension de-listed on Chrome webstore?

### ISSUE THREAD

**Issue by DarkSector** [kagisearch/browser_extensions#84]
Seems like the extension is no longer available - https://chromewebstore.google.com/detail/kagi-search-for-chrome/cdglnehniifkbagbbombnjghhcihifij?hl=en-US

Asked on HN as well - https://news.ycombinator.com/item?id=41028924

**Comment by vprelovac** [comment]
It has taken us by surprise as it happened yesterday (on Saturday) without any warning.

![image](https://github.com/user-attachments/assets/7f459c62-00db-4ed5-979f-f82dba1c6ab7)

The team is working to address this.

**Comment by hughobrien** [comment]
The updated extension, which to meet the Google policy, removes FastGPT and Summarizer features, is currently in review with Google.

**Comment by hughobrien** [comment]
Closing this as the extension is back, though without some of the summariser features unfortunately (google policy)

**Comment by mrzv** [comment]
Are there plans to make another extension with the summarizer features? That was far more useful to me than the incognito search.

**Comment by hughobrien** [comment]
Planned yes, too early to give a commitment on a date though. I don't expect it to be much of a lift.
