### ISSUE TITLE
Firefox summarize function does not ask user permission to access activeTab

### ISSUE THREAD

**Issue by super0nashwan** [kagisearch/browser_extensions#85]
OS: Windows 11 Pro N build 23H2 22631.4037
Browser: Firefox 129.0.2

Expected behaviour: -
When right clicking in a web page and selecting the Kagi Summarize option (that is added by this extension), a pop up window opens and the page is summarized via a call to Kagi's summarize service.

Observed behaviour: -
The window pops up and displays a spinner and the error "You can't summarize without allowing access to the currently active tab." No prompt to grant access is created by the browser. The only permission listed under the extension management permissions tab is "Access your data for https://kagi.com" with no option to enable access to the active tab.  As such, the summarize function has to be invoked by the !sum bang instead.

Potential fix: -
Assuming my ancient install of Firefox doesn't have some weird permissions/privacy flag switched, that I've forgotten about... The required permission "activeTab" is listed in the Firefox manifest.json under "optional_permissions".
I'm a hobbyist coder, but ChatGPT4o suggests moving the permission to the "permissions" part of the manifest so the user can grant (or deny) it on installation.
Or in "summarize_result.js" the function `requestPageSummary()` (which generates the above error message) could be updated to try `browser.permissions.request({ permissions: ["activeTab"] })` if `hasTabAccess` is False.
Additionally, I asked Claude Opus to make suggestions as well (putting my Ultimate sub to good use!). It says: "Make sure to include the tabs permission in the permissions array. The activeTab permission requires the tabs permission as a prerequisite." If that is correct, the "tabs" permission is missing from manifest.json.

**Comment by vprelovac** [comment]
Can you try your solution and confirm it solves the problem?

**Comment by super0nashwan** [comment]
Might be a good opportunity to learn about extension dev tools, sure 🙂 Will be a few days before I can make some time though.

**Comment by vprelovac** [comment]
Please do test and then submit a PR so we can incorporate into the extension. Thanks!
